/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'phamkyit' at '6/25/16 10:18 AM' with Gradle 2.14
 *
 * @author phamkyit, @date 6/25/16 10:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
